# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.11
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_hasher_obj', [dirname(__file__)])
        except ImportError:
            import _hasher_obj
            return _hasher_obj
        if fp is not None:
            try:
                _mod = imp.load_module('_hasher_obj', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _hasher_obj = swig_import_helper()
    del swig_import_helper
else:
    import _hasher_obj
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _hasher_obj.delete_SwigPyIterator
    __del__ = lambda self : None;
    def value(self): return _hasher_obj.SwigPyIterator_value(self)
    def incr(self, n=1): return _hasher_obj.SwigPyIterator_incr(self, n)
    def decr(self, n=1): return _hasher_obj.SwigPyIterator_decr(self, n)
    def distance(self, *args): return _hasher_obj.SwigPyIterator_distance(self, *args)
    def equal(self, *args): return _hasher_obj.SwigPyIterator_equal(self, *args)
    def copy(self): return _hasher_obj.SwigPyIterator_copy(self)
    def next(self): return _hasher_obj.SwigPyIterator_next(self)
    def __next__(self): return _hasher_obj.SwigPyIterator___next__(self)
    def previous(self): return _hasher_obj.SwigPyIterator_previous(self)
    def advance(self, *args): return _hasher_obj.SwigPyIterator_advance(self, *args)
    def __eq__(self, *args): return _hasher_obj.SwigPyIterator___eq__(self, *args)
    def __ne__(self, *args): return _hasher_obj.SwigPyIterator___ne__(self, *args)
    def __iadd__(self, *args): return _hasher_obj.SwigPyIterator___iadd__(self, *args)
    def __isub__(self, *args): return _hasher_obj.SwigPyIterator___isub__(self, *args)
    def __add__(self, *args): return _hasher_obj.SwigPyIterator___add__(self, *args)
    def __sub__(self, *args): return _hasher_obj.SwigPyIterator___sub__(self, *args)
    def __iter__(self): return self
SwigPyIterator_swigregister = _hasher_obj.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class VectorString(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, VectorString, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, VectorString, name)
    __repr__ = _swig_repr
    def iterator(self): return _hasher_obj.VectorString_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _hasher_obj.VectorString___nonzero__(self)
    def __bool__(self): return _hasher_obj.VectorString___bool__(self)
    def __len__(self): return _hasher_obj.VectorString___len__(self)
    def pop(self): return _hasher_obj.VectorString_pop(self)
    def __getslice__(self, *args): return _hasher_obj.VectorString___getslice__(self, *args)
    def __setslice__(self, *args): return _hasher_obj.VectorString___setslice__(self, *args)
    def __delslice__(self, *args): return _hasher_obj.VectorString___delslice__(self, *args)
    def __delitem__(self, *args): return _hasher_obj.VectorString___delitem__(self, *args)
    def __getitem__(self, *args): return _hasher_obj.VectorString___getitem__(self, *args)
    def __setitem__(self, *args): return _hasher_obj.VectorString___setitem__(self, *args)
    def append(self, *args): return _hasher_obj.VectorString_append(self, *args)
    def empty(self): return _hasher_obj.VectorString_empty(self)
    def size(self): return _hasher_obj.VectorString_size(self)
    def clear(self): return _hasher_obj.VectorString_clear(self)
    def swap(self, *args): return _hasher_obj.VectorString_swap(self, *args)
    def get_allocator(self): return _hasher_obj.VectorString_get_allocator(self)
    def begin(self): return _hasher_obj.VectorString_begin(self)
    def end(self): return _hasher_obj.VectorString_end(self)
    def rbegin(self): return _hasher_obj.VectorString_rbegin(self)
    def rend(self): return _hasher_obj.VectorString_rend(self)
    def pop_back(self): return _hasher_obj.VectorString_pop_back(self)
    def erase(self, *args): return _hasher_obj.VectorString_erase(self, *args)
    def __init__(self, *args): 
        this = _hasher_obj.new_VectorString(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _hasher_obj.VectorString_push_back(self, *args)
    def front(self): return _hasher_obj.VectorString_front(self)
    def back(self): return _hasher_obj.VectorString_back(self)
    def assign(self, *args): return _hasher_obj.VectorString_assign(self, *args)
    def resize(self, *args): return _hasher_obj.VectorString_resize(self, *args)
    def insert(self, *args): return _hasher_obj.VectorString_insert(self, *args)
    def reserve(self, *args): return _hasher_obj.VectorString_reserve(self, *args)
    def capacity(self): return _hasher_obj.VectorString_capacity(self)
    __swig_destroy__ = _hasher_obj.delete_VectorString
    __del__ = lambda self : None;
VectorString_swigregister = _hasher_obj.VectorString_swigregister
VectorString_swigregister(VectorString)

class VectorIfStreamP(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, VectorIfStreamP, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, VectorIfStreamP, name)
    __repr__ = _swig_repr
    def iterator(self): return _hasher_obj.VectorIfStreamP_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _hasher_obj.VectorIfStreamP___nonzero__(self)
    def __bool__(self): return _hasher_obj.VectorIfStreamP___bool__(self)
    def __len__(self): return _hasher_obj.VectorIfStreamP___len__(self)
    def pop(self): return _hasher_obj.VectorIfStreamP_pop(self)
    def __getslice__(self, *args): return _hasher_obj.VectorIfStreamP___getslice__(self, *args)
    def __setslice__(self, *args): return _hasher_obj.VectorIfStreamP___setslice__(self, *args)
    def __delslice__(self, *args): return _hasher_obj.VectorIfStreamP___delslice__(self, *args)
    def __delitem__(self, *args): return _hasher_obj.VectorIfStreamP___delitem__(self, *args)
    def __getitem__(self, *args): return _hasher_obj.VectorIfStreamP___getitem__(self, *args)
    def __setitem__(self, *args): return _hasher_obj.VectorIfStreamP___setitem__(self, *args)
    def append(self, *args): return _hasher_obj.VectorIfStreamP_append(self, *args)
    def empty(self): return _hasher_obj.VectorIfStreamP_empty(self)
    def size(self): return _hasher_obj.VectorIfStreamP_size(self)
    def clear(self): return _hasher_obj.VectorIfStreamP_clear(self)
    def swap(self, *args): return _hasher_obj.VectorIfStreamP_swap(self, *args)
    def get_allocator(self): return _hasher_obj.VectorIfStreamP_get_allocator(self)
    def begin(self): return _hasher_obj.VectorIfStreamP_begin(self)
    def end(self): return _hasher_obj.VectorIfStreamP_end(self)
    def rbegin(self): return _hasher_obj.VectorIfStreamP_rbegin(self)
    def rend(self): return _hasher_obj.VectorIfStreamP_rend(self)
    def pop_back(self): return _hasher_obj.VectorIfStreamP_pop_back(self)
    def erase(self, *args): return _hasher_obj.VectorIfStreamP_erase(self, *args)
    def __init__(self, *args): 
        this = _hasher_obj.new_VectorIfStreamP(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _hasher_obj.VectorIfStreamP_push_back(self, *args)
    def front(self): return _hasher_obj.VectorIfStreamP_front(self)
    def back(self): return _hasher_obj.VectorIfStreamP_back(self)
    def assign(self, *args): return _hasher_obj.VectorIfStreamP_assign(self, *args)
    def resize(self, *args): return _hasher_obj.VectorIfStreamP_resize(self, *args)
    def insert(self, *args): return _hasher_obj.VectorIfStreamP_insert(self, *args)
    def reserve(self, *args): return _hasher_obj.VectorIfStreamP_reserve(self, *args)
    def capacity(self): return _hasher_obj.VectorIfStreamP_capacity(self)
    __swig_destroy__ = _hasher_obj.delete_VectorIfStreamP
    __del__ = lambda self : None;
VectorIfStreamP_swigregister = _hasher_obj.VectorIfStreamP_swigregister
VectorIfStreamP_swigregister(VectorIfStreamP)

class HasherObject(_object):
    """Proxy of C++ HasherObject class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, HasherObject, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, HasherObject, name)
    __repr__ = _swig_repr
    def __init__(self): 
        """__init__(HasherObject self) -> HasherObject"""
        this = _hasher_obj.new_HasherObject()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _hasher_obj.delete_HasherObject
    __del__ = lambda self : None;
    def read_update_files(self):
        """read_update_files(HasherObject self) -> int"""
        return _hasher_obj.HasherObject_read_update_files(self)

    def load_hashcodes(self):
        """load_hashcodes(HasherObject self) -> int"""
        return _hasher_obj.HasherObject_load_hashcodes(self)

    def load_itq_model(self):
        """load_itq_model(HasherObject self) -> int"""
        return _hasher_obj.HasherObject_load_itq_model(self)

    def read_feats_from_disk(self, *args):
        """read_feats_from_disk(HasherObject self, std::string filename) -> Mat"""
        return _hasher_obj.HasherObject_read_feats_from_disk(self, *args)

    def set_query_feats_from_disk(self, *args):
        """set_query_feats_from_disk(HasherObject self, std::string filename)"""
        return _hasher_obj.HasherObject_set_query_feats_from_disk(self, *args)

    def compute_hashcodes_from_feats(self, *args):
        """compute_hashcodes_from_feats(HasherObject self, Mat feats) -> unsigned int *"""
        return _hasher_obj.HasherObject_compute_hashcodes_from_feats(self, *args)

    def find_knn(self):
        """find_knn(HasherObject self)"""
        return _hasher_obj.HasherObject_find_knn(self)

    def find_knn_from_feats(self, *args):
        """find_knn_from_feats(HasherObject self, Mat query_feats)"""
        return _hasher_obj.HasherObject_find_knn_from_feats(self, *args)

    def set_paths(self):
        """set_paths(HasherObject self)"""
        return _hasher_obj.HasherObject_set_paths(self)

    def set_topk(self, *args):
        """set_topk(HasherObject self, int _top_k)"""
        return _hasher_obj.HasherObject_set_topk(self, *args)

    def set_ratio(self, *args):
        """set_ratio(HasherObject self, float _ratio)"""
        return _hasher_obj.HasherObject_set_ratio(self, *args)

    def set_bit_num(self, *args):
        """set_bit_num(HasherObject self, int _bit_num)"""
        return _hasher_obj.HasherObject_set_bit_num(self, *args)

    def set_norm(self, *args):
        """set_norm(HasherObject self, int _norm)"""
        return _hasher_obj.HasherObject_set_norm(self, *args)

    def set_feature_dim(self, *args):
        """set_feature_dim(HasherObject self, int _feature_dim)"""
        return _hasher_obj.HasherObject_set_feature_dim(self, *args)

    def set_base_modelpath(self, *args):
        """set_base_modelpath(HasherObject self, std::string _base_modelpath)"""
        return _hasher_obj.HasherObject_set_base_modelpath(self, *args)

    def set_base_updatepath(self, *args):
        """set_base_updatepath(HasherObject self, std::string _base_updatepath)"""
        return _hasher_obj.HasherObject_set_base_updatepath(self, *args)

    def set_outputfile(self, *args):
        """set_outputfile(HasherObject self, std::string _outname)"""
        return _hasher_obj.HasherObject_set_outputfile(self, *args)

    def init_feature_mat(self):
        """init_feature_mat(HasherObject self)"""
        return _hasher_obj.HasherObject_init_feature_mat(self)

    def fill_data_nums_accum(self):
        """fill_data_nums_accum(HasherObject self)"""
        return _hasher_obj.HasherObject_fill_data_nums_accum(self)

    def clean_compfeat_files(self):
        """clean_compfeat_files(HasherObject self)"""
        return _hasher_obj.HasherObject_clean_compfeat_files(self)

HasherObject_swigregister = _hasher_obj.HasherObject_swigregister
HasherObject_swigregister(HasherObject)

# This file is compatible with both classic and new-style classes.


