# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.11
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_hasher_obj_py', [dirname(__file__)])
        except ImportError:
            import _hasher_obj_py
            return _hasher_obj_py
        if fp is not None:
            try:
                _mod = imp.load_module('_hasher_obj_py', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _hasher_obj_py = swig_import_helper()
    del swig_import_helper
else:
    import _hasher_obj_py
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _hasher_obj_py.delete_SwigPyIterator
    __del__ = lambda self : None;
    def value(self): return _hasher_obj_py.SwigPyIterator_value(self)
    def incr(self, n=1): return _hasher_obj_py.SwigPyIterator_incr(self, n)
    def decr(self, n=1): return _hasher_obj_py.SwigPyIterator_decr(self, n)
    def distance(self, *args): return _hasher_obj_py.SwigPyIterator_distance(self, *args)
    def equal(self, *args): return _hasher_obj_py.SwigPyIterator_equal(self, *args)
    def copy(self): return _hasher_obj_py.SwigPyIterator_copy(self)
    def next(self): return _hasher_obj_py.SwigPyIterator_next(self)
    def __next__(self): return _hasher_obj_py.SwigPyIterator___next__(self)
    def previous(self): return _hasher_obj_py.SwigPyIterator_previous(self)
    def advance(self, *args): return _hasher_obj_py.SwigPyIterator_advance(self, *args)
    def __eq__(self, *args): return _hasher_obj_py.SwigPyIterator___eq__(self, *args)
    def __ne__(self, *args): return _hasher_obj_py.SwigPyIterator___ne__(self, *args)
    def __iadd__(self, *args): return _hasher_obj_py.SwigPyIterator___iadd__(self, *args)
    def __isub__(self, *args): return _hasher_obj_py.SwigPyIterator___isub__(self, *args)
    def __add__(self, *args): return _hasher_obj_py.SwigPyIterator___add__(self, *args)
    def __sub__(self, *args): return _hasher_obj_py.SwigPyIterator___sub__(self, *args)
    def __iter__(self): return self
SwigPyIterator_swigregister = _hasher_obj_py.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class HasherObjectPy(_object):
    """Proxy of C++ HasherObjectPy class"""
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, HasherObjectPy, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, HasherObjectPy, name)
    __repr__ = _swig_repr
    def __init__(self): 
        """__init__(HasherObjectPy self) -> HasherObjectPy"""
        this = _hasher_obj_py.new_HasherObjectPy()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _hasher_obj_py.delete_HasherObjectPy
    __del__ = lambda self : None;
    def read_update_files(self):
        """read_update_files(HasherObjectPy self) -> int"""
        return _hasher_obj_py.HasherObjectPy_read_update_files(self)

    def load_hashcodes(self):
        """load_hashcodes(HasherObjectPy self) -> int"""
        return _hasher_obj_py.HasherObjectPy_load_hashcodes(self)

    def load_itq_model(self):
        """load_itq_model(HasherObjectPy self) -> int"""
        return _hasher_obj_py.HasherObjectPy_load_itq_model(self)

    def set_query_feats_from_disk(self, *args):
        """set_query_feats_from_disk(HasherObjectPy self, string filename)"""
        return _hasher_obj_py.HasherObjectPy_set_query_feats_from_disk(self, *args)

    def find_knn(self):
        """find_knn(HasherObjectPy self)"""
        return _hasher_obj_py.HasherObjectPy_find_knn(self)

    def set_paths(self):
        """set_paths(HasherObjectPy self)"""
        return _hasher_obj_py.HasherObjectPy_set_paths(self)

    def set_topk(self, *args):
        """set_topk(HasherObjectPy self, int _top_k)"""
        return _hasher_obj_py.HasherObjectPy_set_topk(self, *args)

    def set_ratio(self, *args):
        """set_ratio(HasherObjectPy self, float _ratio)"""
        return _hasher_obj_py.HasherObjectPy_set_ratio(self, *args)

    def set_bit_num(self, *args):
        """set_bit_num(HasherObjectPy self, int _bit_num)"""
        return _hasher_obj_py.HasherObjectPy_set_bit_num(self, *args)

    def set_norm(self, *args):
        """set_norm(HasherObjectPy self, int _norm)"""
        return _hasher_obj_py.HasherObjectPy_set_norm(self, *args)

    def set_feature_dim(self, *args):
        """set_feature_dim(HasherObjectPy self, int _feature_dim)"""
        return _hasher_obj_py.HasherObjectPy_set_feature_dim(self, *args)

    def set_base_modelpath(self, *args):
        """set_base_modelpath(HasherObjectPy self, string _base_modelpath)"""
        return _hasher_obj_py.HasherObjectPy_set_base_modelpath(self, *args)

    def set_base_updatepath(self, *args):
        """set_base_updatepath(HasherObjectPy self, string _base_updatepath)"""
        return _hasher_obj_py.HasherObjectPy_set_base_updatepath(self, *args)

    def set_outputfile(self, *args):
        """set_outputfile(HasherObjectPy self, string _outname)"""
        return _hasher_obj_py.HasherObjectPy_set_outputfile(self, *args)

HasherObjectPy_swigregister = _hasher_obj_py.HasherObjectPy_swigregister
HasherObjectPy_swigregister(HasherObjectPy)

# This file is compatible with both classic and new-style classes.


